name: Build
on: [push, workflow_dispatch]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Get repository code
              uses: actions/checkout@v3
            - name: Install deps
              uses: npm ci
            - name: Build project
              run: npm run build
            - name: Upload artifact
              uses: actions/upload-artifact@v4
              with:
                path: build
                name: build-files
